version: 2.0
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: ubuntu:16.04

    

    steps:
      - checkout
      - run: apt-get update 
      - run: apt-get install -y build-essential libssl-dev
      - run: git fetch --unshallow || true
      - run: touch aclocal.m4
      - run: touch configure
      - run: find . -name '*.in' -print -exec touch '{}' ';'
      - run: sh ./configure
      - run: make

